USE Budweg_Database;
GO

EXEC sp_rename 'EMPLOYEE.FrontName', 'FirstName', 'COLUMN';
GO

ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_Employee_Building;
ALTER TABLE EMPLOYEE DROP COLUMN BuildingId;
GO

ALTER TABLE REGISTRATION ADD BuildingId INT NOT NULL;
ALTER TABLE REGISTRATION ADD CONSTRAINT FK_Registration_Building 
	FOREIGN KEY (BuildingId) REFERENCES BUILDING(BuildingId);

GO

INSERT INTO REGISTRATION (Arrival, EmployeeId, BuildingId) 
	VALUES (GETDATE(), 1, 1);

GO

SELECT * FROM EMPLOYEE;
SELECT * FROM REGISTRATION;