USE Budweg_Database;
GO

ALTER TABLE EMPLOYEE DROP CONSTRAINT FK_Employee_Building;
ALTER TABLE EMPLOYEE DROP COLUMN BuildingId;
GO

ALTER TABLE REGISTRATION ADD BuildingId INT NOT NULL;
ALTER TABLE REGISTRATION ADD CONSTRAINT FK_Registration_Building 
	FOREIGN KEY (BuildingId) REFERENCES BUILDING(BuildingId);

GO

INSERT INTO REGISTRATION (Arrival, EmployeeId, BuildingId) 
	VALUES (GETDATE(), 1, 1);

SELECT * FROM REGISTRATION;